# Editor
map ctrl+shift+r load_config_file
map f2 launch --cwd=current "$EDITOR" .

# Transparency Adjustment
map alt+- set_background_opacity -0.1
map alt+= set_background_opacity +0.1
map alt+shift+= set_background_opacity 0.9
