# Scrollback
scrollback_lines 20000

# Enable cursor trail
cursor_trail 3

# Enable trasperent background
background_opacity 0.9

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes

# BEGIN_KITTY_FONTS
include fonts.conf
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_KEYBINDS
include keybinds.conf
# END_KITTY_THEME


